### PR TITLE
Pikaday sync

### PR DESCRIPTION
**Pull request by kevinbarnett**

### CODE REVIEW

**Comment by kevinbarnett** [comment]
@NicolasZanotti @mohamed-sadek @voxmachina we could really use some of the new features like date range and theme – I would like to sync up w/ master. Any objections?

**Comment by NicolasZanotti** [comment]
Could be that we don't have any custom features active anymore. Do you of any @mohamed-sadek ?

**Comment by mohamed-sadek** [comment]
We're not using any of the custom features now, no.

**Comment by NicolasZanotti** [comment]
I'd be down with dumping all our stuff and using a new fork of the latest Pikaday release. Up to you @kevinbarnett :+1:

**Comment by voxmachina** [comment]
:+1:

**Pull request merged**
